twig:
    file_name_pattern: '*.twig'
    form_themes: ['bootstrap_5_layout.html.twig']
    globals:
        supabase_bucket: '%env(default::SUPABASE_BUCKET)%'
        supabase_public_url: '%env(default::SUPABASE_PUBLIC_URL)%'

when@test:
    twig:
        strict_variables: true
