<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260914104711 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE position_access_rules (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, operator VARCHAR(20) NOT NULL, compare_value JSON DEFAULT NULL, position_id INT NOT NULL, attribute_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_69543F26DD842E46 ON position_access_rules (position_id)');
        $this->addSql('CREATE INDEX IDX_69543F26B6E62EFA ON position_access_rules (attribute_id)');
        $this->addSql('ALTER TABLE position_access_rules ADD CONSTRAINT FK_69543F26DD842E46 FOREIGN KEY (position_id) REFERENCES positions (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE position_access_rules ADD CONSTRAINT FK_69543F26B6E62EFA FOREIGN KEY (attribute_id) REFERENCES attributes (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE position_access_rules DROP CONSTRAINT FK_69543F26DD842E46');
        $this->addSql('ALTER TABLE position_access_rules DROP CONSTRAINT FK_69543F26B6E62EFA');
        $this->addSql('DROP TABLE position_access_rules');
    }
}
