<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260909134237 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Drop task-tracker tables; reshape projects; add positions, discussion posts, and attribute category lookup.';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE attribute_categories (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(100) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_3E95410D5E237E06 ON attribute_categories (name)');
        $this->addSql('CREATE TABLE discussion_posts (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, content TEXT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, position_id INT NOT NULL, author_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_47C241CFDD842E46 ON discussion_posts (position_id)');
        $this->addSql('CREATE INDEX IDX_47C241CFF675F31B ON discussion_posts (author_id)');
        $this->addSql('CREATE TABLE positions (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, title VARCHAR(255) NOT NULL, short_description TEXT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('ALTER TABLE discussion_posts ADD CONSTRAINT FK_47C241CFDD842E46 FOREIGN KEY (position_id) REFERENCES positions (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE discussion_posts ADD CONSTRAINT FK_47C241CFF675F31B FOREIGN KEY (author_id) REFERENCES users (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE comments DROP CONSTRAINT fk_5f9e962a8db60186');
        $this->addSql('ALTER TABLE comments DROP CONSTRAINT fk_5f9e962af675f31b');
        $this->addSql('ALTER TABLE tasks DROP CONSTRAINT fk_50586597166d1f9c');
        $this->addSql('ALTER TABLE tasks DROP CONSTRAINT fk_50586597f4bd7827');
        $this->addSql('ALTER TABLE tasks DROP CONSTRAINT fk_5058659712469de2');
        $this->addSql('DROP TABLE category');
        $this->addSql('DROP TABLE comments');
        $this->addSql('DROP TABLE tasks');
        $this->addSql('ALTER TABLE projects ADD start_date DATE DEFAULT NULL');
        $this->addSql('UPDATE projects SET start_date = created_at::date WHERE start_date IS NULL');
        $this->addSql('ALTER TABLE projects ALTER COLUMN start_date SET NOT NULL');
        $this->addSql('ALTER TABLE projects ADD end_date DATE DEFAULT NULL');
        $this->addSql("ALTER TABLE projects ADD technology_tags JSON DEFAULT '[]'::json NOT NULL");
        $this->addSql('ALTER TABLE projects ALTER technology_tags DROP DEFAULT');
        $this->addSql("INSERT INTO attribute_categories (name) VALUES ('Personal Information'), ('Certification'), ('Domain Knowledge'), ('Soft Skills')");
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE category (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, color VARCHAR(50) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_64c19c15e237e06 ON category (name)');
        $this->addSql('CREATE TABLE comments (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, content TEXT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, task_id INT NOT NULL, author_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_5f9e962af675f31b ON comments (author_id)');
        $this->addSql('CREATE INDEX idx_5f9e962a8db60186 ON comments (task_id)');
        $this->addSql('CREATE TABLE tasks (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, title VARCHAR(255) NOT NULL, description TEXT DEFAULT NULL, status VARCHAR(50) NOT NULL, priority VARCHAR(50) NOT NULL, due_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, project_id INT NOT NULL, assigned_to_id INT DEFAULT NULL, category_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_50586597166d1f9c ON tasks (project_id)');
        $this->addSql('CREATE INDEX idx_50586597f4bd7827 ON tasks (assigned_to_id)');
        $this->addSql('CREATE INDEX idx_5058659712469de2 ON tasks (category_id)');
        $this->addSql('ALTER TABLE comments ADD CONSTRAINT fk_5f9e962a8db60186 FOREIGN KEY (task_id) REFERENCES tasks (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE comments ADD CONSTRAINT fk_5f9e962af675f31b FOREIGN KEY (author_id) REFERENCES users (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE tasks ADD CONSTRAINT fk_50586597166d1f9c FOREIGN KEY (project_id) REFERENCES projects (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE tasks ADD CONSTRAINT fk_50586597f4bd7827 FOREIGN KEY (assigned_to_id) REFERENCES users (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE tasks ADD CONSTRAINT fk_5058659712469de2 FOREIGN KEY (category_id) REFERENCES category (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE discussion_posts DROP CONSTRAINT FK_47C241CFDD842E46');
        $this->addSql('ALTER TABLE discussion_posts DROP CONSTRAINT FK_47C241CFF675F31B');
        $this->addSql('DROP TABLE attribute_categories');
        $this->addSql('DROP TABLE discussion_posts');
        $this->addSql('DROP TABLE positions');
        $this->addSql('ALTER TABLE projects DROP start_date');
        $this->addSql('ALTER TABLE projects DROP end_date');
        $this->addSql('ALTER TABLE projects DROP technology_tags');
    }
}
