<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260912075101 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE attributes (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, description TEXT DEFAULT NULL, type VARCHAR(50) NOT NULL, is_built_in BOOLEAN NOT NULL, options JSON NOT NULL, version INT DEFAULT NULL, category_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_319B9E705E237E06 ON attributes (name)');
        $this->addSql('CREATE INDEX IDX_319B9E7012469DE2 ON attributes (category_id)');
        $this->addSql('ALTER TABLE attributes ADD CONSTRAINT FK_319B9E7012469DE2 FOREIGN KEY (category_id) REFERENCES attribute_categories (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE attributes DROP CONSTRAINT FK_319B9E7012469DE2');
        $this->addSql('DROP TABLE attributes');
    }
}
