<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260914104807 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE cvs (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, status VARCHAR(20) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, version INT DEFAULT 1 NOT NULL, user_id INT NOT NULL, position_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_5B9529DA76ED395 ON cvs (user_id)');
        $this->addSql('CREATE INDEX IDX_5B9529DDD842E46 ON cvs (position_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_cvs_user_position ON cvs (user_id, position_id)');
        $this->addSql('ALTER TABLE cvs ADD CONSTRAINT FK_5B9529DA76ED395 FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE cvs ADD CONSTRAINT FK_5B9529DDD842E46 FOREIGN KEY (position_id) REFERENCES positions (id) ON DELETE CASCADE NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE cvs DROP CONSTRAINT FK_5B9529DA76ED395');
        $this->addSql('ALTER TABLE cvs DROP CONSTRAINT FK_5B9529DDD842E46');
        $this->addSql('DROP TABLE cvs');
    }
}
