<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260914104617 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE position_attributes (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, sort_order INT NOT NULL, position_id INT NOT NULL, attribute_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_1F7AB2F0DD842E46 ON position_attributes (position_id)');
        $this->addSql('CREATE INDEX IDX_1F7AB2F0B6E62EFA ON position_attributes (attribute_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_position_attributes_position_attribute ON position_attributes (position_id, attribute_id)');
        $this->addSql('ALTER TABLE position_attributes ADD CONSTRAINT FK_1F7AB2F0DD842E46 FOREIGN KEY (position_id) REFERENCES positions (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE position_attributes ADD CONSTRAINT FK_1F7AB2F0B6E62EFA FOREIGN KEY (attribute_id) REFERENCES attributes (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE position_attributes DROP CONSTRAINT FK_1F7AB2F0DD842E46');
        $this->addSql('ALTER TABLE position_attributes DROP CONSTRAINT FK_1F7AB2F0B6E62EFA');
        $this->addSql('DROP TABLE position_attributes');
    }
}
