<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260914104836 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE cv_likes (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, recruiter_id INT NOT NULL, curriculum_vitae_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_C6CE9E62156BE243 ON cv_likes (recruiter_id)');
        $this->addSql('CREATE INDEX IDX_C6CE9E624AF29A35 ON cv_likes (curriculum_vitae_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_cv_likes_recruiter_cv ON cv_likes (recruiter_id, curriculum_vitae_id)');
        $this->addSql('ALTER TABLE cv_likes ADD CONSTRAINT FK_C6CE9E62156BE243 FOREIGN KEY (recruiter_id) REFERENCES users (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE cv_likes ADD CONSTRAINT FK_C6CE9E624AF29A35 FOREIGN KEY (curriculum_vitae_id) REFERENCES cvs (id) ON DELETE CASCADE NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE cv_likes DROP CONSTRAINT FK_C6CE9E62156BE243');
        $this->addSql('ALTER TABLE cv_likes DROP CONSTRAINT FK_C6CE9E624AF29A35');
        $this->addSql('DROP TABLE cv_likes');
    }
}
