<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260914082014 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE attribute_values (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, value JSON DEFAULT NULL, user_id INT NOT NULL, attribute_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_184662BCA76ED395 ON attribute_values (user_id)');
        $this->addSql('CREATE INDEX IDX_184662BCB6E62EFA ON attribute_values (attribute_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_attribute_values_user_attribute ON attribute_values (user_id, attribute_id)');
        $this->addSql('ALTER TABLE attribute_values ADD CONSTRAINT FK_184662BCA76ED395 FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE attribute_values ADD CONSTRAINT FK_184662BCB6E62EFA FOREIGN KEY (attribute_id) REFERENCES attributes (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE attribute_values DROP CONSTRAINT FK_184662BCA76ED395');
        $this->addSql('ALTER TABLE attribute_values DROP CONSTRAINT FK_184662BCB6E62EFA');
        $this->addSql('DROP TABLE attribute_values');
    }
}
