# yaml-language-server: $schema=../vendor/symfony/dependency-injection/Loader/schema/services.schema.json

# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.
# See also https://symfony.com/doc/current/service_container/import.html

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    env(SUPABASE_S3_ENDPOINT): ''
    env(SUPABASE_S3_REGION): ''
    env(SUPABASE_ACCESS_KEY): ''
    env(SUPABASE_SECRET_KEY): ''
    env(SUPABASE_BUCKET): ''
    env(SUPABASE_PUBLIC_URL): ''
    env(SALESFORCE_LOGIN_URL): ''
    env(SALESFORCE_CLIENT_ID): ''
    env(SALESFORCE_CLIENT_SECRET): ''
    env(SALESFORCE_USERNAME): ''
    env(SALESFORCE_PASSWORD): ''
    env(ODOO_EXPORT_TOKEN): ''

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
